:begin
CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
:commit
:begin
UNWIND [{_id:4, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/333", name:"Homo sapiens", externalId:"EOL:333"}}, {_id:6, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:8, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:10, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:13, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/333", name:"Homo sapiens", externalId:"EOL:333"}}, {_id:15, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:17, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:19, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:21, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/123", name:"Homo erectus", externalId:"EOL:123"}}, {_id:23, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:25, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:27, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:29, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/123", name:"Homo erectus", externalId:"EOL:123"}}, {_id:31, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:64, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:40, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:38, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/888", name:"Homo erectus", externalId:"EOL:888"}}, {_id:68, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:74, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:70, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Taxon;
UNWIND [{_id:57, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:35, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:71, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:55, properties:{path:"pathElem1 | pathElem 2", name:"Blo blaaus", externalId:"no:match"}}, {_id:63, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:49, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/555", name:"Canis lupus", externalId:"EOL:555"}}, {_id:42, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:59, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:47, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/888", name:"Homo erectus", externalId:"EOL:888"}}, {_id:44, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:66, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/123", name:"Homo erectus", externalId:"EOL:123"}}, {_id:61, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:65, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:73, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/888", name:"Homo erectus", externalId:"EOL:888"}}, {_id:51, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:67, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:53, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}, {_id:69, properties:{path:"pathElem1 | pathElem 2", name:"Blo blaaus", externalId:"no:match"}}, {_id:33, properties:{path:"preyPathElem1 | preyPathElem2", externalUrl:"http://eol.org/pages/666", name:"Felis domesticus", externalId:"EOL:666"}}, {_id:72, properties:{path:"preyPathElem1 | preyPathElem2", name:"Blah blahuuuu", externalId:"no:match"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Taxon;
UNWIND [{_id:62, properties:{path:"pathElem1 | pathElem 2", externalUrl:"http://eol.org/pages/333", name:"Homo sapiens", externalId:"EOL:333"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Taxon;
UNWIND [{_id:0, properties:{titleNS:"globi:some/namespace/myStudy", title:"myStudy", type:"StudyNode"}}, {_id:36, properties:{titleNS:"globi:some/namespace/yourStudy", title:"yourStudy", type:"StudyNode"}}, {_id:45, properties:{titleNS:"globi:some/namespace/yourStudy2", title:"yourStudy2", type:"StudyNode"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Reference;
UNWIND [{_id:1, properties:{lastSeenAt:"0", shouldResolveReferences:"true", citation:"<http://example.com>", namespace:"some/namespace", format:"globi", archiveURI:"http://example.com"}}, {_id:2, properties:{externalId:"http://example.com"}}, {_id:3, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}, {_id:5, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:7, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:9, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:11, properties:{altitude:-60, latitude:12, locality:"some locale", type:"LocationNode", localityId:"some:localeid", longitude:-45.9}}, {_id:12, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}, {_id:14, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:16, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:18, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:20, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}, {_id:22, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:24, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:26, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:28, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}, {_id:30, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:43, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:56, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:46, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties;
UNWIND [{_id:48, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:54, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}, {_id:41, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:39, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:37, properties:{sexLabel:"female", physiologicalStateLabel:"DIGESTATE", bodyPartId:"GLOBI:BONE", stomachVolumeInMilliLiter:666, physiologicalStateId:"GLOBI:DIGESTATE", sexId:"some:female", lengthInMm:12, lifeStageId:"GLOBI:JUVENILE", bodyPartLabel:"BONE", type:"SpecimenNode", lifeStageLabel:"JUVENILE"}}, {_id:34, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:58, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:52, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:32, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:60, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}, {_id:50, properties:{type:"SpecimenNode", volumeInMilliLiter:124}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties;
:commit
:begin
UNWIND [{start: {_id:0}, end: {_id:12}, properties:{eventDate:"1992-03-30T08:00:00Z"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:REFUTES]->(end) SET r += row.properties;
UNWIND [{start: {_id:0}, end: {_id:1}, properties:{}}, {start: {_id:36}, end: {_id:1}, properties:{}}, {start: {_id:45}, end: {_id:1}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:IN_DATASET]->(end) SET r += row.properties;
UNWIND [{start: {_id:5}, end: {_id:3}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:7}, end: {_id:3}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:9}, end: {_id:3}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:14}, end: {_id:12}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:34}, end: {_id:28}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:16}, end: {_id:12}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:32}, end: {_id:28}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:60}, end: {_id:54}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:18}, end: {_id:12}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:30}, end: {_id:28}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:24}, end: {_id:20}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:48}, end: {_id:46}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:39}, end: {_id:37}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:56}, end: {_id:54}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:26}, end: {_id:20}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:22}, end: {_id:20}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:43}, end: {_id:37}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:58}, end: {_id:54}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:41}, end: {_id:37}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}, {start: {_id:50}, end: {_id:46}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:EATEN_BY]->(end) SET r += row.properties;
UNWIND [{start: {_id:52}, end: {_id:46}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002471", label:"eatenBy", inverted:"true"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:EATEN_BY]->(end) SET r += row.properties;
UNWIND [{start: {_id:0}, end: {_id:3}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:0}, end: {_id:5}, properties:{}}, {start: {_id:0}, end: {_id:7}, properties:{}}, {start: {_id:0}, end: {_id:9}, properties:{}}, {start: {_id:0}, end: {_id:14}, properties:{}}, {start: {_id:0}, end: {_id:16}, properties:{}}, {start: {_id:0}, end: {_id:54}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:0}, end: {_id:20}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:36}, end: {_id:39}, properties:{}}, {start: {_id:0}, end: {_id:56}, properties:{}}, {start: {_id:45}, end: {_id:50}, properties:{}}, {start: {_id:0}, end: {_id:58}, properties:{}}, {start: {_id:0}, end: {_id:60}, properties:{}}, {start: {_id:36}, end: {_id:43}, properties:{}}, {start: {_id:36}, end: {_id:41}, properties:{}}, {start: {_id:0}, end: {_id:34}, properties:{}}, {start: {_id:0}, end: {_id:22}, properties:{}}, {start: {_id:0}, end: {_id:24}, properties:{}}, {start: {_id:0}, end: {_id:32}, properties:{}}, {start: {_id:0}, end: {_id:30}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:COLLECTED]->(end) SET r += row.properties;
UNWIND [{start: {_id:45}, end: {_id:52}, properties:{}}, {start: {_id:0}, end: {_id:18}, properties:{}}, {start: {_id:0}, end: {_id:28}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:45}, end: {_id:46}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:45}, end: {_id:48}, properties:{}}, {start: {_id:0}, end: {_id:26}, properties:{}}, {start: {_id:36}, end: {_id:37}, properties:{eventDate:"1992-03-30T08:00:00Z"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:COLLECTED]->(end) SET r += row.properties;
UNWIND [{start: {_id:3}, end: {_id:11}, properties:{}}, {start: {_id:37}, end: {_id:11}, properties:{}}, {start: {_id:12}, end: {_id:11}, properties:{}}, {start: {_id:46}, end: {_id:11}, properties:{}}, {start: {_id:28}, end: {_id:11}, properties:{}}, {start: {_id:54}, end: {_id:11}, properties:{}}, {start: {_id:20}, end: {_id:11}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:COLLECTED_AT]->(end) SET r += row.properties;
UNWIND [{start: {_id:3}, end: {_id:4}, properties:{}}, {start: {_id:5}, end: {_id:6}, properties:{}}, {start: {_id:7}, end: {_id:8}, properties:{}}, {start: {_id:9}, end: {_id:10}, properties:{}}, {start: {_id:12}, end: {_id:13}, properties:{}}, {start: {_id:14}, end: {_id:15}, properties:{}}, {start: {_id:16}, end: {_id:17}, properties:{}}, {start: {_id:52}, end: {_id:53}, properties:{}}, {start: {_id:54}, end: {_id:55}, properties:{}}, {start: {_id:20}, end: {_id:21}, properties:{}}, {start: {_id:30}, end: {_id:31}, properties:{}}, {start: {_id:41}, end: {_id:42}, properties:{}}, {start: {_id:22}, end: {_id:23}, properties:{}}, {start: {_id:60}, end: {_id:61}, properties:{}}, {start: {_id:37}, end: {_id:38}, properties:{}}, {start: {_id:48}, end: {_id:49}, properties:{}}, {start: {_id:43}, end: {_id:44}, properties:{}}, {start: {_id:58}, end: {_id:59}, properties:{}}, {start: {_id:28}, end: {_id:29}, properties:{}}, {start: {_id:39}, end: {_id:40}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ORIGINALLY_DESCRIBED_AS]->(end) SET r += row.properties;
UNWIND [{start: {_id:56}, end: {_id:57}, properties:{}}, {start: {_id:24}, end: {_id:25}, properties:{}}, {start: {_id:50}, end: {_id:51}, properties:{}}, {start: {_id:32}, end: {_id:33}, properties:{}}, {start: {_id:18}, end: {_id:19}, properties:{}}, {start: {_id:26}, end: {_id:27}, properties:{}}, {start: {_id:46}, end: {_id:47}, properties:{}}, {start: {_id:34}, end: {_id:35}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ORIGINALLY_DESCRIBED_AS]->(end) SET r += row.properties;
UNWIND [{start: {_id:0}, end: {_id:3}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:0}, end: {_id:5}, properties:{}}, {start: {_id:0}, end: {_id:7}, properties:{}}, {start: {_id:0}, end: {_id:9}, properties:{}}, {start: {_id:0}, end: {_id:14}, properties:{}}, {start: {_id:0}, end: {_id:16}, properties:{}}, {start: {_id:0}, end: {_id:22}, properties:{}}, {start: {_id:36}, end: {_id:39}, properties:{}}, {start: {_id:0}, end: {_id:20}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:0}, end: {_id:24}, properties:{}}, {start: {_id:45}, end: {_id:46}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:45}, end: {_id:50}, properties:{}}, {start: {_id:0}, end: {_id:60}, properties:{}}, {start: {_id:0}, end: {_id:58}, properties:{}}, {start: {_id:0}, end: {_id:34}, properties:{}}, {start: {_id:0}, end: {_id:18}, properties:{}}, {start: {_id:0}, end: {_id:54}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:36}, end: {_id:37}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:36}, end: {_id:41}, properties:{}}, {start: {_id:36}, end: {_id:43}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:SUPPORTS]->(end) SET r += row.properties;
UNWIND [{start: {_id:0}, end: {_id:28}, properties:{eventDate:"1992-03-30T08:00:00Z"}}, {start: {_id:45}, end: {_id:52}, properties:{}}, {start: {_id:0}, end: {_id:32}, properties:{}}, {start: {_id:0}, end: {_id:26}, properties:{}}, {start: {_id:0}, end: {_id:30}, properties:{}}, {start: {_id:45}, end: {_id:48}, properties:{}}, {start: {_id:0}, end: {_id:56}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:SUPPORTS]->(end) SET r += row.properties;
UNWIND [{start: {_id:3}, end: {_id:5}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:3}, end: {_id:7}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:3}, end: {_id:9}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:12}, end: {_id:14}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:12}, end: {_id:16}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:54}, end: {_id:58}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:20}, end: {_id:26}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:12}, end: {_id:18}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:54}, end: {_id:60}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:46}, end: {_id:50}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:37}, end: {_id:41}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:28}, end: {_id:30}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:37}, end: {_id:43}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:20}, end: {_id:22}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:20}, end: {_id:24}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:54}, end: {_id:56}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:46}, end: {_id:52}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:28}, end: {_id:34}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:46}, end: {_id:48}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}, {start: {_id:28}, end: {_id:32}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ATE]->(end) SET r += row.properties;
UNWIND [{start: {_id:37}, end: {_id:39}, properties:{iri:"http://purl.obolibrary.org/obo/RO_0002470", label:"eats"}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ATE]->(end) SET r += row.properties;
UNWIND [{start: {_id:1}, end: {_id:2}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:HAS_EXTERNAL_ID]->(end) SET r += row.properties;
UNWIND [{start: {_id:16}, end: {_id:64}, properties:{}}, {start: {_id:28}, end: {_id:66}, properties:{}}, {start: {_id:3}, end: {_id:62}, properties:{}}, {start: {_id:30}, end: {_id:63}, properties:{}}, {start: {_id:43}, end: {_id:72}, properties:{}}, {start: {_id:56}, end: {_id:63}, properties:{}}, {start: {_id:18}, end: {_id:70}, properties:{}}, {start: {_id:7}, end: {_id:64}, properties:{}}, {start: {_id:9}, end: {_id:65}, properties:{}}, {start: {_id:34}, end: {_id:68}, properties:{}}, {start: {_id:48}, end: {_id:63}, properties:{}}, {start: {_id:24}, end: {_id:64}, properties:{}}, {start: {_id:54}, end: {_id:69}, properties:{}}, {start: {_id:58}, end: {_id:64}, properties:{}}, {start: {_id:22}, end: {_id:63}, properties:{}}, {start: {_id:26}, end: {_id:71}, properties:{}}, {start: {_id:46}, end: {_id:73}, properties:{}}, {start: {_id:14}, end: {_id:63}, properties:{}}, {start: {_id:41}, end: {_id:64}, properties:{}}, {start: {_id:32}, end: {_id:64}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:CLASSIFIED_AS]->(end) SET r += row.properties;
UNWIND [{start: {_id:20}, end: {_id:66}, properties:{}}, {start: {_id:12}, end: {_id:62}, properties:{}}, {start: {_id:5}, end: {_id:63}, properties:{}}, {start: {_id:52}, end: {_id:74}, properties:{}}, {start: {_id:37}, end: {_id:73}, properties:{}}, {start: {_id:39}, end: {_id:63}, properties:{}}, {start: {_id:60}, end: {_id:67}, properties:{}}, {start: {_id:50}, end: {_id:64}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:CLASSIFIED_AS]->(end) SET r += row.properties;
:commit
:begin
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
:commit
:begin
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
:commit
