package org.eol.globi.domain;

public enum InteractType implements RelType {
    PREYS_UPON, PARASITE_OF, HAS_HOST, INTERACTS_WITH, HOST_OF, POLLINATES, PERCHING_ON, ATE, SYMBIONT_OF, PREYED_UPON_BY, POLLINATED_BY, EATEN_BY, HAS_PARASITE, PERCHED_ON_BY, HAS_PATHOGEN, PATHOGEN_OF
}
