name: Java CI
on: [push]
jobs:
  build-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8,21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn test --activate-profiles core
  build-neo4j-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn test --activate-profiles core,neo4j
